/*
 * Generates tools/selector-probe.js from the live adapter definitions, so the
 * probe can never drift from what the extension actually uses.
 *
 *   node tools/make-probe.js
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
['schema', 'redact', 'classify', 'adapters', 'surfaces'].forEach((f) => {
  vm.runInThisContext(fs.readFileSync(path.join(ROOT, 'src', 'core', f + '.js'), 'utf8'), { filename: f + '.js' });
});
const VG = globalThis.VG;

// Strip the functions; the probe only needs the declarative parts.
const data = VG.BUILTIN_ADAPTERS.map((a) => ({
  id: a.id,
  label: a.label,
  revision: a.revision,
  hosts: a.hosts,
  selectors: a.selectors,
  surfaces: (a.surfaces || []).map((s) => ({
    id: s.id, label: s.label, primary: !!s.primary, url: s.url || null,
    dom: s.dom || null, name: s.name || null, agentType: s.agentType || null
  })),
  sharedDom: a.sharedDom || [],
  account: a.account || {}
}));

const body = `/*
 * Vantage, selector probe   (generated by tools/make-probe.js; do not edit)
 * Config revision ${VG.CONFIG_REVISION}
 *
 * HOW TO USE, the context matters, do not skip steps 1-3
 *   1. Open claude.ai / chatgpt.com / gemini.google.com and SIGN IN.
 *   2. Open a conversation that ALREADY HAS at least one exchange in it.
 *      On an empty chat the turn selectors cannot match and the report is
 *      meaningless.
 *   3. TYPE A FEW CHARACTERS into the composer and leave them there. Several
 *      of these UIs only render the send button once there is text.
 *   4. DevTools (F12) -> Console -> paste this whole file -> Enter.
 *   5. Copy the report it prints.
 *
 * It only reports which CSS selectors resolve and how many elements matched.
 * It reads no prompt text, no response text, and sends nothing anywhere.
 */
(function () {
  'use strict';
  var ADAPTERS = ${JSON.stringify(data, null, 2)};

  function hostMatches(host, pattern) {
    var h = String(host || '').toLowerCase();
    var p = String(pattern || '').toLowerCase().replace(/^\\*\\./, '');
    return h === p || h.endsWith('.' + p);
  }

  var adapter = null;
  for (var i = 0; i < ADAPTERS.length && !adapter; i++) {
    for (var j = 0; j < ADAPTERS[i].hosts.length; j++) {
      if (hostMatches(location.hostname, ADAPTERS[i].hosts[j])) { adapter = ADAPTERS[i]; break; }
    }
  }
  if (!adapter) {
    console.log('Vantage probe: no adapter covers ' + location.hostname);
    return;
  }

  function probe(list) {
    var out = { hit: null, index: -1, count: 0, tried: (list || []).length };
    for (var k = 0; k < (list || []).length; k++) {
      try {
        var els = document.querySelectorAll(list[k]);
        if (els.length) { out.hit = list[k]; out.index = k; out.count = els.length; return out; }
      } catch (e) { /* invalid selector */ }
    }
    return out;
  }

  var GROUPS = ['composer', 'send', 'thread', 'userTurn', 'assistantTurn', 'model', 'regenerate', 'attachment'];
  var CRITICAL = { composer: 1, send: 1 };

  // What this page can actually answer for. A selector that cannot match in
  // the current context is not a broken selector.
  var turnsVisible = document.querySelectorAll(
    '[data-message-author-role],[data-turn],[data-testid*="message" i],' +
    'user-query,model-response,div[class*="font-claude" i],div[class*="font-user" i]'
  ).length;
  var hasConversation = turnsVisible > 0;
  var composerHasText = (function () {
    var el = probe(adapter.selectors.composer).hit
      ? document.querySelector(probe(adapter.selectors.composer).hit) : null;
    if (!el) return false;
    var t = el.value !== undefined ? el.value : (el.innerText || '');
    return String(t).trim().length > 0;
  })();
  var ANSWERABLE = {
    composer: true, send: true, thread: true, model: true,
    userTurn: hasConversation, assistantTurn: hasConversation,
    regenerate: hasConversation, attachment: false
  };

  var lines = [];
  var rows = [];
  var broken = [];
  var degraded = [];

  lines.push('VANTAGE SELECTOR PROBE');
  lines.push('site      : ' + adapter.label + '  (' + adapter.id + ' rev ' + adapter.revision + ')');
  lines.push('host      : ' + location.hostname);
  lines.push('path      : ' + location.pathname.replace(/[0-9a-f-]{8,}/gi, '<id>'));
  lines.push('when      : ' + new Date().toISOString());
  lines.push('context   : ' + (hasConversation ? turnsVisible + ' turns visible' : 'EMPTY CHAT, open one with an exchange in it') +
    ', composer ' + (composerHasText ? 'has text' : 'is EMPTY (send may be hidden)'));
  lines.push('');
  lines.push('SELECTORS');

  GROUPS.forEach(function (g) {
    var r = probe(adapter.selectors[g]);
    var status;
    if (r.hit && r.index === 0) status = 'OK      ';
    else if (r.hit) status = 'FALLBACK';
    else if (!ANSWERABLE[g]) status = 'n/a     ';
    else status = 'MISSING ';

    if (status === 'MISSING ' && CRITICAL[g]) broken.push(g);
    else if (status === 'MISSING ') degraded.push(g);
    else if (status === 'FALLBACK') degraded.push(g + ' (fallback ' + r.index + ')');

    lines.push(
      '  ' + status + ' ' + g.padEnd(14) +
      (r.hit ? 'x' + r.count + '  <- ' + r.hit
        : (ANSWERABLE[g] ? 'none of ' + r.tried + ' selectors matched'
          : 'not checkable in this context'))
    );
    rows.push({ group: g, status: status.trim(), matched: r.hit, index: r.index, count: r.count });
  });

  lines.push('');
  lines.push('SURFACE RULES');
  var pathAndQuery = location.pathname + location.search;
  adapter.surfaces.forEach(function (s) {
    var urlOk = s.url ? new RegExp(s.url, 'i').test(pathAndQuery) : null;
    var domOk = s.dom ? !!probe(s.dom).hit : null;
    var nameOk = s.name ? !!probe(s.name).hit : null;
    var active = (s.url ? urlOk : true) && (s.dom ? domOk : true) && (s.url || s.dom);
    lines.push(
      '  ' + (active ? 'ACTIVE  ' : '        ') + (s.id + (s.primary ? ' (primary)' : '')).padEnd(26) +
      (s.url ? 'url:' + (urlOk ? 'yes' : 'no') + ' ' : '') +
      (s.dom ? 'dom:' + (domOk ? 'yes' : 'no') + ' ' : '') +
      (s.name ? 'name-selector:' + (nameOk ? 'found' : 'not found') : '')
    );
  });

  /*
   * When a selector misses, report what is actually on the page so the fix can
   * be made from one report instead of another round trip. Attributes only,
   * never text content, except aria-label which is interface chrome.
   */
  function describe(el) {
    var bits = [el.tagName.toLowerCase()];
    if (el.id) bits.push('#' + el.id);
    var testid = el.getAttribute('data-testid') || el.getAttribute('data-test-id');
    if (testid) bits.push('[data-testid="' + testid + '"]');
    var al = el.getAttribute('aria-label');
    if (al) bits.push('[aria-label="' + al.slice(0, 40) + '"]');
    var t = el.getAttribute('type');
    if (t) bits.push('[type="' + t + '"]');
    var cls = (el.getAttribute('class') || '').split(/\\s+/).filter(function (c) {
      return c && c.length < 24 && !/^(css|sc)-/.test(c);
    }).slice(0, 3);
    if (cls.length) bits.push('.' + cls.join('.'));
    return bits.join('');
  }

  function candidates(label, scope, sel, limit) {
    if (!scope) return;
    var found = [];
    try { found = [].slice.call(scope.querySelectorAll(sel)); } catch (e) { return; }
    if (!found.length) return;
    lines.push('');
    lines.push('CANDIDATES for ' + label + ' (' + found.length + ' found, showing ' + Math.min(limit, found.length) + ')');
    found.slice(0, limit).forEach(function (el) { lines.push('  ' + describe(el)); });
  }

  var composerEl = probe(adapter.selectors.composer).hit
    ? document.querySelector(probe(adapter.selectors.composer).hit) : null;
  var threadEl = probe(adapter.selectors.thread).hit
    ? document.querySelector(probe(adapter.selectors.thread).hit) : null;
  var lastAssistant = (function () {
    var h = probe(adapter.selectors.assistantTurn).hit;
    if (!h) return null;
    var all = document.querySelectorAll(h);
    return all.length ? all[all.length - 1] : null;
  })();

  if (broken.indexOf('send') !== -1 || degraded.indexOf('send') !== -1) {
    var form = composerEl && composerEl.closest
      ? (composerEl.closest('form, footer, div[class*="composer" i]') || document.body)
      : document.body;
    candidates('send, buttons near the composer', form, 'button', 8);
  }
  if (broken.indexOf('model') !== -1 || degraded.some(function (d) { return d.indexOf('model') === 0; })) {
    candidates('model, buttons outside the thread', document, 'header button, nav button, [class*="header" i] button', 8);
  }
  if (degraded.indexOf('regenerate') !== -1 || broken.indexOf('regenerate') !== -1) {
    candidates('regenerate, buttons in the last reply', lastAssistant && lastAssistant.parentElement, 'button', 10);
  }
  if (!probe(adapter.account.emailFrom).hit && !probe(adapter.account.planFrom).hit) {
    candidates('account, buttons that look like an account control', document,
      '[data-testid*="account" i], [aria-label*="account" i], [class*="account" i], nav [class*="profile" i]', 5);
  }

  lines.push('');
  lines.push('OTHER');
  var sh = probe(adapter.sharedDom);
  lines.push('  shared-with-team marker : ' + (sh.hit ? 'found <- ' + sh.hit : 'not found'));
  var em = probe(adapter.account.emailFrom);
  var pl = probe(adapter.account.planFrom);
  lines.push('  account email element   : ' + (em.hit ? 'found <- ' + em.hit : 'not found'));
  lines.push('  account plan element    : ' + (pl.hit ? 'found <- ' + pl.hit : 'not found'));

  lines.push('');
  if (!hasConversation) {
    lines.push('NOTE: empty chat, turn, regenerate and attachment selectors were not checked.');
  }
  if (!composerHasText && broken.indexOf('send') !== -1) {
    lines.push('NOTE: the composer is empty. On several of these sites the send button only');
    lines.push('      exists once you have typed something, so this may be a false alarm.');
  }
  if (broken.length) {
    lines.push('VERDICT: BROKEN, ' + broken.join(', ') + ' did not resolve. Capture will not work on this site.');
  } else if (degraded.length) {
    lines.push('VERDICT: WORKS, DEGRADED, ' + degraded.join(', ') + '. Capture works; some metrics will be missing.');
  } else {
    lines.push('VERDICT: HEALTHY, every selector matched on its first choice.');
  }
  lines.push('');
  lines.push('Send the block above back. It contains no prompt or response text.');

  var report = lines.join('\\n');
  console.log(report);
  try {
    copy(report);
    console.log('%cCopied to clipboard.', 'color:#16a34a;font-weight:600');
  } catch (e) {
    console.log('(select the text above and copy it)');
  }
  return { adapter: adapter.id, rows: rows, broken: broken, degraded: degraded };
})();
`;

fs.writeFileSync(path.join(__dirname, 'selector-probe.js'), body);
console.log('wrote tools/selector-probe.js  (config revision ' + VG.CONFIG_REVISION + ', ' + data.length + ' adapters)');
