/*
 * Vantage, policy generator.
 *
 *   node tools/make-policy.js [config.json]
 *
 * Reads a policy payload, validates every key against policy/managed_schema.json,
 * and writes deployment files for Windows, macOS and Linux into deploy/.
 *
 * Written as a generator because the three formats disagree about types in ways
 * that are easy to get wrong by hand. The registry needs REG_DWORD for numbers
 * and booleans and a JSON string for anything structured, macOS needs a plist
 * value, and Linux takes the JSON as it stands.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DEPLOY = path.join(ROOT, 'deploy');
const EXT_ID = (() => {
  const m = JSON.parse(fs.readFileSync(path.join(ROOT, 'manifest.json'), 'utf8'));
  const crypto = require('crypto');
  const hash = crypto.createHash('sha256').update(Buffer.from(m.key, 'base64')).digest();
  let id = '';
  for (let i = 0; i < 16; i++) {
    id += String.fromCharCode(97 + (hash[i] >> 4));
    id += String.fromCharCode(97 + (hash[i] & 0x0f));
  }
  return id;
})();

const schema = JSON.parse(fs.readFileSync(path.join(ROOT, 'policy', 'managed_schema.json'), 'utf8'));
const src = process.argv[2] || path.join(DEPLOY, 'policy.example.json');
const config = JSON.parse(fs.readFileSync(src, 'utf8'));

/* ------------------------------ validation ------------------------------ */

const problems = [];
Object.keys(config).forEach((k) => {
  const def = schema.properties[k];
  if (!def) { problems.push(`unknown key: ${k}`); return; }
  const v = config[k];
  const t = def.type;
  const actual = Array.isArray(v) ? 'array' : typeof v;
  const want = t === 'integer' ? 'number' : t;
  if (want && actual !== want) problems.push(`${k}: expected ${t}, got ${actual}`);
  if (t === 'integer' && !Number.isInteger(v)) problems.push(`${k}: must be a whole number`);
  if (def.enum && def.enum.indexOf(v) === -1) problems.push(`${k}: must be one of ${def.enum.join(', ')}`);
  if (def.minimum !== undefined && v < def.minimum) problems.push(`${k}: below minimum ${def.minimum}`);
  if (def.maximum !== undefined && v > def.maximum) problems.push(`${k}: above maximum ${def.maximum}`);
});

if (problems.length) {
  console.error('\nPolicy rejected:');
  problems.forEach((p) => console.error('  ' + p));
  console.error('\nValid keys are listed in policy/managed_schema.json\n');
  process.exit(1);
}

const placeholders = JSON.stringify(config).match(/REPLACE/g);
const warn = placeholders ? `  ${placeholders.length} REPLACE placeholder(s) still present\n` : '';

/* ------------------------------- Windows -------------------------------- */

function regEscape(s) {
  return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function regValue(v) {
  if (typeof v === 'boolean') return `dword:${v ? '00000001' : '00000000'}`;
  if (typeof v === 'number') return `dword:${(v >>> 0).toString(16).padStart(8, '0')}`;
  if (typeof v === 'string') return `"${regEscape(v)}"`;
  return `"${regEscape(JSON.stringify(v))}"`;   // objects and arrays go in as JSON
}

function windows(browser) {
  const vendor = browser === 'edge' ? 'Microsoft\\\\Edge' : 'Google\\\\Chrome';
  const L = [];
  L.push('Windows Registry Editor Version 5.00');
  L.push('');
  L.push(`; Vantage policy for ${browser === 'edge' ? 'Microsoft Edge' : 'Google Chrome'}, machine wide.`);
  L.push('; Generated by tools/make-policy.js. Edit deploy/policy.example.json and regenerate.');
  L.push('');
  L.push('; Force install from an internally hosted update manifest');
  L.push(`[HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\${vendor}\\ExtensionInstallForcelist]`);
  L.push(`"1"="${EXT_ID};https://REPLACE.internal/vantage/updates.xml"`);
  L.push('');
  L.push('; Extension configuration');
  L.push(`[HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\${vendor}\\3rdparty\\extensions\\${EXT_ID}\\policy]`);
  Object.keys(config).forEach((k) => L.push(`"${k}"=${regValue(config[k])}`));

  if (config.uploadEnabled && config.uploadUrl) {
    let host = 'REPLACE';
    try { host = new URL(config.uploadUrl.replace(/\{[a-z]+\}/g, 'x')).host; } catch (e) { /* keep */ }
    L.push('');
    L.push('; Grant the upload endpoint so no permission prompt appears');
    L.push(`[HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\${vendor}]`);
    const settings = {};
    settings[EXT_ID] = { runtime_allowed_hosts: ['*://' + host] };
    L.push(`"ExtensionSettings"="${regEscape(JSON.stringify(settings))}"`);
  }
  L.push('');
  return L.join('\r\n');
}

/* -------------------------------- Linux --------------------------------- */

function linux() {
  const doc = {
    ExtensionInstallForcelist: [`${EXT_ID};https://REPLACE.internal/vantage/updates.xml`],
    '3rdparty': { extensions: {} }
  };
  doc['3rdparty'].extensions[EXT_ID] = config;
  if (config.uploadEnabled && config.uploadUrl) {
    let host = 'REPLACE';
    try { host = new URL(config.uploadUrl.replace(/\{[a-z]+\}/g, 'x')).host; } catch (e) { /* keep */ }
    doc.ExtensionSettings = {};
    doc.ExtensionSettings[EXT_ID] = { runtime_allowed_hosts: ['*://' + host] };
  }
  return JSON.stringify(doc, null, 2) + '\n';
}

/* -------------------------------- macOS --------------------------------- */

function macos() {
  const L = [];
  L.push('#!/bin/bash');
  L.push('# Vantage policy for macOS. Generated by tools/make-policy.js.');
  L.push('# For production use an MDM configuration profile with the same values.');
  L.push('# Swap com.microsoft.Edge for com.google.Chrome to target Chrome.');
  L.push('set -euo pipefail');
  L.push('');
  L.push('DOMAIN=com.microsoft.Edge');
  L.push(`EXT=${EXT_ID}`);
  L.push('');
  L.push('sudo defaults write "$DOMAIN" ExtensionInstallForcelist -array \\');
  L.push('  "$EXT;https://REPLACE.internal/vantage/updates.xml"');
  L.push('');
  L.push('# Extension configuration, written as a single JSON blob');
  L.push("sudo defaults write \"$DOMAIN\" 3rdparty -dict-add extensions '" +
    JSON.stringify({ [EXT_ID]: config }) + "'");
  if (config.uploadEnabled && config.uploadUrl) {
    let host = 'REPLACE';
    try { host = new URL(config.uploadUrl.replace(/\{[a-z]+\}/g, 'x')).host; } catch (e) { /* keep */ }
    L.push('');
    L.push('sudo defaults write "$DOMAIN" ExtensionSettings -dict-add "$EXT" \\');
    L.push(`  '${JSON.stringify({ runtime_allowed_hosts: ['*://' + host] })}'`);
  }
  L.push('');
  L.push('echo "Restart the browser, then confirm at edge://policy"');
  L.push('');
  return L.join('\n');
}

/* -------------------------------- write --------------------------------- */

fs.mkdirSync(path.join(DEPLOY, 'windows'), { recursive: true });
fs.mkdirSync(path.join(DEPLOY, 'linux'), { recursive: true });
fs.mkdirSync(path.join(DEPLOY, 'macos'), { recursive: true });

const out = [
  ['windows/vantage-edge.reg', windows('edge')],
  ['windows/vantage-chrome.reg', windows('chrome')],
  ['linux/vantage.json', linux()],
  ['macos/vantage-policy.sh', macos()]
];
out.forEach(([f, body]) => {
  const p = path.join(DEPLOY, f);
  fs.writeFileSync(p, body);
  if (f.endsWith('.sh')) fs.chmodSync(p, 0o755);
  console.log('  deploy/' + f);
});

console.log('\nextension id  ' + EXT_ID);
console.log('keys          ' + Object.keys(config).length + ' validated against the policy schema');
if (warn) process.stdout.write(warn);
