/*
 * Vantage, selector probe   (generated by tools/make-probe.js; do not edit)
 * Config revision 6
 *
 * HOW TO USE, the context matters, do not skip steps 1-3
 *   1. Open claude.ai / chatgpt.com / gemini.google.com and SIGN IN.
 *   2. Open a conversation that ALREADY HAS at least one exchange in it.
 *      On an empty chat the turn selectors cannot match and the report is
 *      meaningless.
 *   3. TYPE A FEW CHARACTERS into the composer and leave them there. Several
 *      of these UIs only render the send button once there is text.
 *   4. DevTools (F12) -> Console -> paste this whole file -> Enter.
 *   5. Copy the report it prints.
 *
 * It only reports which CSS selectors resolve and how many elements matched.
 * It reads no prompt text, no response text, and sends nothing anywhere.
 */
(function () {
  'use strict';
  var ADAPTERS = [
  {
    "id": "claude",
    "label": "Claude",
    "revision": 5,
    "hosts": [
      "claude.ai"
    ],
    "selectors": {
      "composer": [
        "div[contenteditable=\"true\"][data-testid]",
        "div[contenteditable=\"true\"].ProseMirror",
        "fieldset div[contenteditable=\"true\"]",
        "div[contenteditable=\"true\"]"
      ],
      "send": [
        "button[aria-label=\"Send message\"]",
        "button[aria-label*=\"Send\" i]",
        "button[type=\"submit\"]"
      ],
      "thread": [
        "main",
        "div.flex-1.flex.flex-col"
      ],
      "userTurn": [
        "[data-testid=\"user-message\"]",
        "div.font-user-message"
      ],
      "assistantTurn": [
        "[data-testid=\"assistant-message\"]",
        "div.font-claude-message",
        "div.font-claude-response"
      ],
      "model": [
        "[data-testid=\"model-selector-dropdown\"]",
        "button[data-testid*=\"model\" i]"
      ],
      "regenerate": [
        "button[aria-label*=\"Retry\" i]",
        "button[aria-label*=\"Regenerate\" i]"
      ],
      "attachment": [
        "[data-testid=\"file-thumbnail\"]",
        "div[data-testid*=\"attachment\" i]"
      ]
    },
    "surfaces": [
      {
        "id": "project",
        "label": "Project",
        "primary": true,
        "url": "\\/project\\/([0-9a-zA-Z-]{6,})",
        "dom": null,
        "name": [
          "[data-testid=\"project-name\"]",
          "header h1",
          "main h1"
        ],
        "agentType": "project"
      },
      {
        "id": "artifact",
        "label": "Artifact",
        "primary": false,
        "url": null,
        "dom": [
          "[data-testid=\"artifact-panel\"]",
          "div[class*=\"artifact\" i][role=\"region\"]"
        ],
        "name": null,
        "agentType": null
      },
      {
        "id": "connector",
        "label": "Connector / MCP",
        "primary": false,
        "url": null,
        "dom": [
          "[data-testid*=\"connector\" i]",
          "button[aria-label*=\"tools\" i][aria-pressed=\"true\"]"
        ],
        "name": null,
        "agentType": null
      },
      {
        "id": "deep_research",
        "label": "Research mode",
        "primary": false,
        "url": null,
        "dom": [
          "button[aria-pressed=\"true\"][aria-label*=\"Research\" i]",
          "[data-testid*=\"research-toggle\" i][aria-pressed=\"true\"]"
        ],
        "name": null,
        "agentType": null
      }
    ],
    "sharedDom": [
      "[data-testid=\"project-members\"]",
      "[aria-label*=\"Shared with\" i]"
    ],
    "account": {
      "emailFrom": [
        "[data-testid=\"user-menu-email\"]",
        "div[class*=\"account\" i] [class*=\"email\" i]"
      ],
      "planFrom": [
        "[data-testid=\"user-menu-plan\"]",
        "div[class*=\"plan-badge\" i]",
        "[aria-label*=\"plan\" i]"
      ]
    }
  },
  {
    "id": "chatgpt",
    "label": "ChatGPT",
    "revision": 6,
    "hosts": [
      "chatgpt.com",
      "chat.openai.com"
    ],
    "selectors": {
      "composer": [
        "div#prompt-textarea[contenteditable=\"true\"]",
        "textarea#prompt-textarea",
        "form div[contenteditable=\"true\"]"
      ],
      "send": [
        "button[data-testid=\"send-button\"]",
        "button#composer-submit-button",
        "button[aria-label*=\"Send\" i]"
      ],
      "thread": [
        "main",
        "div[role=\"presentation\"]"
      ],
      "userTurn": [
        "[data-message-author-role=\"user\"]",
        "[data-turn=\"user\"]",
        "article[data-turn-id][data-turn=\"user\"]"
      ],
      "assistantTurn": [
        "[data-message-author-role=\"assistant\"]",
        "[data-turn=\"assistant\"]"
      ],
      "model": [
        "button[aria-label*=\"Model\" i]",
        "[data-testid=\"model-switcher-dropdown-button\"]",
        "button[data-testid*=\"model\" i]"
      ],
      "regenerate": [
        "button[data-testid*=\"regenerate\" i]",
        "button[aria-label*=\"Regenerate\" i]",
        "button[aria-label*=\"Try again\" i]"
      ],
      "attachment": [
        "div[data-testid*=\"attachment\" i]",
        "button[aria-label*=\"Remove file\" i]"
      ]
    },
    "surfaces": [
      {
        "id": "project",
        "label": "Project",
        "primary": true,
        "url": "\\/g\\/(g-p-[A-Za-z0-9_-]+)",
        "dom": null,
        "name": [
          "[data-testid=\"project-name\"]",
          "header h1",
          "main h1"
        ],
        "agentType": "project"
      },
      {
        "id": "custom_agent",
        "label": "Custom GPT",
        "primary": true,
        "url": "\\/g\\/(g-(?!p-)[A-Za-z0-9_-]+)",
        "dom": null,
        "name": [
          "[data-testid=\"gizmo-name\"]",
          "header h1",
          "div[class*=\"gizmo\" i] h1"
        ],
        "agentType": "gpt"
      },
      {
        "id": "canvas",
        "label": "Canvas",
        "primary": false,
        "url": null,
        "dom": [
          "[data-testid=\"canvas-panel\"]",
          "section[class*=\"canvas\" i]"
        ],
        "name": null,
        "agentType": null
      },
      {
        "id": "deep_research",
        "label": "Deep research",
        "primary": false,
        "url": null,
        "dom": [
          "button[data-testid*=\"deep-research\" i][aria-pressed=\"true\"]",
          "button[aria-label*=\"Deep research\" i][aria-pressed=\"true\"]"
        ],
        "name": null,
        "agentType": null
      },
      {
        "id": "agent_mode",
        "label": "Agent mode",
        "primary": false,
        "url": null,
        "dom": [
          "[data-testid*=\"agent-mode\" i]",
          "button[aria-label*=\"Agent mode\" i][aria-pressed=\"true\"]"
        ],
        "name": null,
        "agentType": null
      },
      {
        "id": "code_interpreter",
        "label": "Code interpreter",
        "primary": false,
        "url": null,
        "dom": [
          "[data-testid*=\"code-interpreter\" i]",
          "div[class*=\"jupyter\" i]"
        ],
        "name": null,
        "agentType": null
      },
      {
        "id": "search",
        "label": "Web search",
        "primary": false,
        "url": null,
        "dom": [
          "button[aria-label*=\"Search\" i][aria-pressed=\"true\"]",
          "[data-testid*=\"search-toggle\" i][aria-pressed=\"true\"]"
        ],
        "name": null,
        "agentType": null
      }
    ],
    "sharedDom": [
      "[data-testid=\"project-members\"]",
      "[aria-label*=\"Shared\" i][role=\"group\"]"
    ],
    "account": {
      "emailFrom": [
        "[data-testid=\"accounts-profile-button\"] [class*=\"email\" i]",
        "div[class*=\"account-menu\" i] [class*=\"email\" i]"
      ],
      "planFrom": [
        "[data-testid=\"workspace-switcher\"]",
        "button[aria-label*=\"workspace\" i]",
        "div[class*=\"plan\" i]"
      ]
    }
  },
  {
    "id": "gemini",
    "label": "Gemini",
    "revision": 5,
    "hosts": [
      "gemini.google.com"
    ],
    "selectors": {
      "composer": [
        "rich-textarea div[contenteditable=\"true\"]",
        "div.ql-editor[contenteditable=\"true\"]",
        "div[contenteditable=\"true\"][role=\"textbox\"]"
      ],
      "send": [
        "button.send-button",
        "button[aria-label*=\"Send\" i]",
        "button[mattooltip*=\"Send\" i]"
      ],
      "thread": [
        "chat-window",
        "main"
      ],
      "userTurn": [
        "user-query",
        ".query-text"
      ],
      "assistantTurn": [
        "model-response",
        "message-content"
      ],
      "model": [
        "button[data-test-id=\"bard-mode-menu-button\"]",
        "bard-mode-switcher button"
      ],
      "regenerate": [
        "button[aria-label*=\"Regenerate\" i]",
        "button[data-test-id*=\"regenerate\" i]"
      ],
      "attachment": [
        "uploader-file-preview",
        "div[class*=\"file-preview\" i]"
      ]
    },
    "surfaces": [
      {
        "id": "custom_agent",
        "label": "Gem",
        "primary": true,
        "url": "\\/gem\\/([A-Za-z0-9_-]{4,})",
        "dom": null,
        "name": [
          "[data-test-id=\"bot-name\"]",
          "bot-name",
          "header h1"
        ],
        "agentType": "gem"
      },
      {
        "id": "deep_research",
        "label": "Deep research",
        "primary": false,
        "url": null,
        "dom": [
          "[data-test-id*=\"deep-research\" i][aria-pressed=\"true\"]",
          "button[aria-label*=\"Deep Research\" i][aria-pressed=\"true\"]"
        ],
        "name": null,
        "agentType": null
      },
      {
        "id": "canvas",
        "label": "Canvas",
        "primary": false,
        "url": null,
        "dom": [
          "immersive-panel",
          "[data-test-id=\"canvas-panel\"]"
        ],
        "name": null,
        "agentType": null
      }
    ],
    "sharedDom": [
      "[data-test-id*=\"shared\" i]"
    ],
    "account": {
      "emailFrom": [
        "a[aria-label*=\"Google Account\" i]",
        "div[class*=\"gb_\" i][aria-label*=\"@\"]"
      ],
      "planFrom": [
        "[data-test-id*=\"workspace\" i]",
        "div[class*=\"upgrade\" i]"
      ]
    }
  },
  {
    "id": "copilot",
    "label": "Microsoft Copilot",
    "revision": 5,
    "hosts": [
      "copilot.microsoft.com",
      "copilot.cloud.microsoft",
      "m365.cloud.microsoft",
      "www.office.com"
    ],
    "selectors": {
      "composer": [
        "textarea#userInput",
        "div[contenteditable=\"true\"][role=\"textbox\"]",
        "div[contenteditable=\"true\"]"
      ],
      "send": [
        "button[title*=\"Submit\" i]",
        "button[aria-label*=\"Send\" i]",
        "button[type=\"submit\"]"
      ],
      "thread": [
        "main",
        "div[role=\"main\"]"
      ],
      "userTurn": [
        "div[data-content=\"user-message\"]",
        "div[class*=\"userMessage\" i]"
      ],
      "assistantTurn": [
        "div[data-content=\"ai-message\"]",
        "div[class*=\"botMessage\" i]"
      ],
      "model": [],
      "regenerate": [
        "button[aria-label*=\"Regenerate\" i]"
      ],
      "attachment": [
        "div[class*=\"attachment\" i]"
      ]
    },
    "surfaces": [
      {
        "id": "custom_agent",
        "label": "Copilot agent",
        "primary": true,
        "url": "\\/(?:agents?|bizchat\\/agent)\\/([A-Za-z0-9_.-]{4,})",
        "dom": null,
        "name": [
          "[data-testid=\"agent-name\"]",
          "header h1"
        ],
        "agentType": "agent"
      },
      {
        "id": "notebook",
        "label": "Notebook",
        "primary": false,
        "url": null,
        "dom": [
          "[data-testid*=\"notebook\" i]"
        ],
        "name": null,
        "agentType": null
      },
      {
        "id": "search",
        "label": "Work grounding",
        "primary": false,
        "url": null,
        "dom": [
          "button[aria-label*=\"Work\" i][aria-pressed=\"true\"]"
        ],
        "name": null,
        "agentType": null
      }
    ],
    "sharedDom": [],
    "account": {
      "emailFrom": [
        "#mectrl_currentAccount_secondary",
        "[data-testid=\"account-email\"]"
      ],
      "planFrom": [
        "[data-testid=\"copilot-mode-badge\"]",
        "div[class*=\"workBadge\" i]"
      ]
    }
  }
];

  function hostMatches(host, pattern) {
    var h = String(host || '').toLowerCase();
    var p = String(pattern || '').toLowerCase().replace(/^\*\./, '');
    return h === p || h.endsWith('.' + p);
  }

  var adapter = null;
  for (var i = 0; i < ADAPTERS.length && !adapter; i++) {
    for (var j = 0; j < ADAPTERS[i].hosts.length; j++) {
      if (hostMatches(location.hostname, ADAPTERS[i].hosts[j])) { adapter = ADAPTERS[i]; break; }
    }
  }
  if (!adapter) {
    console.log('Vantage probe: no adapter covers ' + location.hostname);
    return;
  }

  function probe(list) {
    var out = { hit: null, index: -1, count: 0, tried: (list || []).length };
    for (var k = 0; k < (list || []).length; k++) {
      try {
        var els = document.querySelectorAll(list[k]);
        if (els.length) { out.hit = list[k]; out.index = k; out.count = els.length; return out; }
      } catch (e) { /* invalid selector */ }
    }
    return out;
  }

  var GROUPS = ['composer', 'send', 'thread', 'userTurn', 'assistantTurn', 'model', 'regenerate', 'attachment'];
  var CRITICAL = { composer: 1, send: 1 };

  // What this page can actually answer for. A selector that cannot match in
  // the current context is not a broken selector.
  var turnsVisible = document.querySelectorAll(
    '[data-message-author-role],[data-turn],[data-testid*="message" i],' +
    'user-query,model-response,div[class*="font-claude" i],div[class*="font-user" i]'
  ).length;
  var hasConversation = turnsVisible > 0;
  var composerHasText = (function () {
    var el = probe(adapter.selectors.composer).hit
      ? document.querySelector(probe(adapter.selectors.composer).hit) : null;
    if (!el) return false;
    var t = el.value !== undefined ? el.value : (el.innerText || '');
    return String(t).trim().length > 0;
  })();
  var ANSWERABLE = {
    composer: true, send: true, thread: true, model: true,
    userTurn: hasConversation, assistantTurn: hasConversation,
    regenerate: hasConversation, attachment: false
  };

  var lines = [];
  var rows = [];
  var broken = [];
  var degraded = [];

  lines.push('VANTAGE SELECTOR PROBE');
  lines.push('site      : ' + adapter.label + '  (' + adapter.id + ' rev ' + adapter.revision + ')');
  lines.push('host      : ' + location.hostname);
  lines.push('path      : ' + location.pathname.replace(/[0-9a-f-]{8,}/gi, '<id>'));
  lines.push('when      : ' + new Date().toISOString());
  lines.push('context   : ' + (hasConversation ? turnsVisible + ' turns visible' : 'EMPTY CHAT, open one with an exchange in it') +
    ', composer ' + (composerHasText ? 'has text' : 'is EMPTY (send may be hidden)'));
  lines.push('');
  lines.push('SELECTORS');

  GROUPS.forEach(function (g) {
    var r = probe(adapter.selectors[g]);
    var status;
    if (r.hit && r.index === 0) status = 'OK      ';
    else if (r.hit) status = 'FALLBACK';
    else if (!ANSWERABLE[g]) status = 'n/a     ';
    else status = 'MISSING ';

    if (status === 'MISSING ' && CRITICAL[g]) broken.push(g);
    else if (status === 'MISSING ') degraded.push(g);
    else if (status === 'FALLBACK') degraded.push(g + ' (fallback ' + r.index + ')');

    lines.push(
      '  ' + status + ' ' + g.padEnd(14) +
      (r.hit ? 'x' + r.count + '  <- ' + r.hit
        : (ANSWERABLE[g] ? 'none of ' + r.tried + ' selectors matched'
          : 'not checkable in this context'))
    );
    rows.push({ group: g, status: status.trim(), matched: r.hit, index: r.index, count: r.count });
  });

  lines.push('');
  lines.push('SURFACE RULES');
  var pathAndQuery = location.pathname + location.search;
  adapter.surfaces.forEach(function (s) {
    var urlOk = s.url ? new RegExp(s.url, 'i').test(pathAndQuery) : null;
    var domOk = s.dom ? !!probe(s.dom).hit : null;
    var nameOk = s.name ? !!probe(s.name).hit : null;
    var active = (s.url ? urlOk : true) && (s.dom ? domOk : true) && (s.url || s.dom);
    lines.push(
      '  ' + (active ? 'ACTIVE  ' : '        ') + (s.id + (s.primary ? ' (primary)' : '')).padEnd(26) +
      (s.url ? 'url:' + (urlOk ? 'yes' : 'no') + ' ' : '') +
      (s.dom ? 'dom:' + (domOk ? 'yes' : 'no') + ' ' : '') +
      (s.name ? 'name-selector:' + (nameOk ? 'found' : 'not found') : '')
    );
  });

  /*
   * When a selector misses, report what is actually on the page so the fix can
   * be made from one report instead of another round trip. Attributes only,
   * never text content, except aria-label which is interface chrome.
   */
  function describe(el) {
    var bits = [el.tagName.toLowerCase()];
    if (el.id) bits.push('#' + el.id);
    var testid = el.getAttribute('data-testid') || el.getAttribute('data-test-id');
    if (testid) bits.push('[data-testid="' + testid + '"]');
    var al = el.getAttribute('aria-label');
    if (al) bits.push('[aria-label="' + al.slice(0, 40) + '"]');
    var t = el.getAttribute('type');
    if (t) bits.push('[type="' + t + '"]');
    var cls = (el.getAttribute('class') || '').split(/\s+/).filter(function (c) {
      return c && c.length < 24 && !/^(css|sc)-/.test(c);
    }).slice(0, 3);
    if (cls.length) bits.push('.' + cls.join('.'));
    return bits.join('');
  }

  function candidates(label, scope, sel, limit) {
    if (!scope) return;
    var found = [];
    try { found = [].slice.call(scope.querySelectorAll(sel)); } catch (e) { return; }
    if (!found.length) return;
    lines.push('');
    lines.push('CANDIDATES for ' + label + ' (' + found.length + ' found, showing ' + Math.min(limit, found.length) + ')');
    found.slice(0, limit).forEach(function (el) { lines.push('  ' + describe(el)); });
  }

  var composerEl = probe(adapter.selectors.composer).hit
    ? document.querySelector(probe(adapter.selectors.composer).hit) : null;
  var threadEl = probe(adapter.selectors.thread).hit
    ? document.querySelector(probe(adapter.selectors.thread).hit) : null;
  var lastAssistant = (function () {
    var h = probe(adapter.selectors.assistantTurn).hit;
    if (!h) return null;
    var all = document.querySelectorAll(h);
    return all.length ? all[all.length - 1] : null;
  })();

  if (broken.indexOf('send') !== -1 || degraded.indexOf('send') !== -1) {
    var form = composerEl && composerEl.closest
      ? (composerEl.closest('form, footer, div[class*="composer" i]') || document.body)
      : document.body;
    candidates('send, buttons near the composer', form, 'button', 8);
  }
  if (broken.indexOf('model') !== -1 || degraded.some(function (d) { return d.indexOf('model') === 0; })) {
    candidates('model, buttons outside the thread', document, 'header button, nav button, [class*="header" i] button', 8);
  }
  if (degraded.indexOf('regenerate') !== -1 || broken.indexOf('regenerate') !== -1) {
    candidates('regenerate, buttons in the last reply', lastAssistant && lastAssistant.parentElement, 'button', 10);
  }
  if (!probe(adapter.account.emailFrom).hit && !probe(adapter.account.planFrom).hit) {
    candidates('account, buttons that look like an account control', document,
      '[data-testid*="account" i], [aria-label*="account" i], [class*="account" i], nav [class*="profile" i]', 5);
  }

  lines.push('');
  lines.push('OTHER');
  var sh = probe(adapter.sharedDom);
  lines.push('  shared-with-team marker : ' + (sh.hit ? 'found <- ' + sh.hit : 'not found'));
  var em = probe(adapter.account.emailFrom);
  var pl = probe(adapter.account.planFrom);
  lines.push('  account email element   : ' + (em.hit ? 'found <- ' + em.hit : 'not found'));
  lines.push('  account plan element    : ' + (pl.hit ? 'found <- ' + pl.hit : 'not found'));

  lines.push('');
  if (!hasConversation) {
    lines.push('NOTE: empty chat, turn, regenerate and attachment selectors were not checked.');
  }
  if (!composerHasText && broken.indexOf('send') !== -1) {
    lines.push('NOTE: the composer is empty. On several of these sites the send button only');
    lines.push('      exists once you have typed something, so this may be a false alarm.');
  }
  if (broken.length) {
    lines.push('VERDICT: BROKEN, ' + broken.join(', ') + ' did not resolve. Capture will not work on this site.');
  } else if (degraded.length) {
    lines.push('VERDICT: WORKS, DEGRADED, ' + degraded.join(', ') + '. Capture works; some metrics will be missing.');
  } else {
    lines.push('VERDICT: HEALTHY, every selector matched on its first choice.');
  }
  lines.push('');
  lines.push('Send the block above back. It contains no prompt or response text.');

  var report = lines.join('\n');
  console.log(report);
  try {
    copy(report);
    console.log('%cCopied to clipboard.', 'color:#16a34a;font-weight:600');
  } catch (e) {
    console.log('(select the text above and copy it)');
  }
  return { adapter: adapter.id, rows: rows, broken: broken, degraded: degraded };
})();
